// <auto-generated />
using Data_Migration;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Data_Migration.Migrations
{
    [DbContext(typeof(MigrationDBContext))]
    [Migration("20240708173342_MigrationSkript_Info_FeldHinzugefuegt")]
    partial class MigrationSkript_Info_FeldHinzugefuegt
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data_Migration.Entities.Abrufberechtigte", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AB_gruppe")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Info_AB")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MigrationSkript_Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("istVerarbeitet")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Abrufberechtigtes");
                });

            modelBuilder.Entity("Data_Migration.Entities.Kdnr", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Anrede")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Hausnr")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kunden_Nr_AB_rel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MigrationSkript_Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name_des_Unternehmens")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ort")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PLZ")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RV_Los")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rechtsform")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("istVerarbeitet")
                        .HasColumnType("boolean");

                    b.Property<string>("zusaetzlicher_Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kdnrs");
                });

            modelBuilder.Entity("Data_Migration.Entities.Organisationsbeauftragten", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Abteilung_Zentraler_Asp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Anrede_Zentraler_Asp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email_Zentraler_Asp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Funktions_postfach")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MigrationSkript_Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Mobilfunknummer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name_Zentraler_Asp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon_Zentraler_Asp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titel_Zentraler_Asp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UUID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Vorname_zentraler_Asp")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("istVerarbeitet")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Organisationsbeauftragtens");
                });

            modelBuilder.Entity("Data_Migration.Entities.Rkto", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("InfoRKTO")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Kunden_NrAB_rel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MigrationSkript_Info")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rechnungskonto_2024")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rechungskonto_2017")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("istVerarbeitet")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Rktos");
                });
#pragma warning restore 612, 618
        }
    }
}
